### PR TITLE
Notion-Enhancer compatibility

### PR DESCRIPTION
**Pull request by haydn-jones**
[Notion-Enhancer](https://github.com/dragonwocky/notion-enhancer) is a popular and awesome mod loader for Notion that supports themes, right-to-left text flow, emoji sets, word counts, and a lot more. It unfortunately does not work with this installation method because it requires the application files to be bundled in an asar file. This can be done with a few trivial changes to the build script and results in no user facing changes whatsoever. 

With these changes in place notion-enhancer works with this installation method.

### CODE REVIEW

**Comment by vtenfys** [comment]
thanks! is there a reason for changing `options.icon` btw?

**Comment by vtenfys** [comment]
sorry, reverting since this seems to break the build - happy if you want to look into this and open another pr :)

**Comment by haydn-jones** [comment]
Sure, I'll investigate. What is going on with the build? I haven't had any issues by people using my fork. I'll check why I touched options.icon.

**Comment by vtenfys** [comment]
> Sure, I'll investigate. What is going on with the build?

thanks!

it seems that adding `--asar` flag to `electron-packager` prevents it from outputting anything to the specified directory (`build/dist`) although no error appears in the terminal (also returns a `0` exit code for success) so not exactly sure what's going wrong.

also, `--asar=true` does not seem to be a documented flag for the next command based on running `electron-installer-debian --help` so i'm not sure what this is supposed to do?

**Comment by vtenfys** [comment]
> I'll check why I touched options.icon.

I figured out the reason after asking my question - the icon exists in both places, and I like your change since there are fewer nested subdirectories, so will keep this - thanks!

**Pull request merged**
