### PR TITLE
Notion-Enhancer compatibility

### PR DESCRIPTION
**Pull request by vtenfys**
Opening this PR again to check whether the build is working and see if this is mergeable, thanks @haydn-jones

### CODE REVIEW

**Comment by vtenfys** [comment]
Unfortunately this is still not working on my end - adding `--asar` prevents the `build/dist` directory from being created. I'm still not sure what is wrong since the `electron-packager` command does not produce any error output and exist with a `0` status code.

**Comment by vtenfys** [comment]
@dragonwocky hey! would you be alright with me directly integrating notion-enhancer into this build script? baking in support would allow me to distribute `deb` packages which are pre-patched with enhancements :)

**Comment by haydn-jones** [comment]
I was going to say, with `notion-enhancer` now supporting unpacked builds my MR probably isn't necessary anymore! Would be quite cool to pass a flag that would build a `notion-enhancer`-ified deb.

**Comment by vtenfys** [comment]
> I was going to say, with notion-enhancer now supporting unpacked builds my MR probably isn't necessary anymore!

ah, that answers [my question here](https://github.com/davidbailey00/notion-deb-builder/issues/17#issuecomment-739262092)!

**Comment by dragonwocky** [comment]
hey @davidbailey00 that's a cool idea.

with how the enhancer works at the moment it might be a little fiddly, because to make it easy to add new mods it works based off a fancy loader that looks up and links downloaded enhancer files by an absolute path somewhere rather than directly inserting the changes into the app folder.
i'm just about to start a rework on the module system though that will bring some pretty major changes to things like file location & format, revamp the theming variables, and significantly decrease the amount of files needed for the enhancer to work. that would make pre-enhanced debs a lot more possible.

i'd say hold off for now but definitely give this a try when v0.11.0 comes out. in theory it would then just need ~~copying the app folder to make an `app.bak`, appending a single `require()` statement to every js file in the `app` folder, and adding in an `enhancer` folder at the same level as the `app` folder~~ running the enhancer apply script with a `--path` flag set to whatever the parent folder of the `app` folder would be during the build process.

so i don't forget about this i've made an issue in the enhancer repo for this too: https://github.com/notion-enhancer/notion-enhancer/issues/321

**Comment by vtenfys** [comment]
thanks! i've been looking into it a bit already before your message but sounds like things will be easier after that release :)

**Pull request closed without merging**
